# SAM configuration file for Order Processing System with X-Ray Tracing
version = 0.1

[default]
[default.global.parameters]
stack_name = "order-processing-v2-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" ProjectName=\"order-processing-v2\""
disable_rollback = false

[default.build.parameters]
cached = true
parallel = true
use_container = false

[default.deploy.parameters]
fail_on_empty_changeset = false
resolve_s3 = true
s3_prefix = "order-processing-v2-dev"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Environment-specific configurations
[staging]
[staging.global.parameters]
stack_name = "order-processing-v2-staging"
parameter_overrides = "Environment=\"staging\" ProjectName=\"order-processing-v2\""

[staging.deploy.parameters]
s3_prefix = "order-processing-v2-staging"

[prod]
[prod.global.parameters]
stack_name = "order-processing-v2-prod"
parameter_overrides = "Environment=\"prod\" ProjectName=\"order-processing-v2\""

[prod.deploy.parameters]
s3_prefix = "order-processing-v2-prod"
